# NB : parameters with x values must be filled in 
ibmwatsonml:
  SPACE_ID: 48cf3358-53bf-478c-8692-d8c11a2d455b
  API_DOMAIN: eu-de.ml.cloud.ibm.com
  API_KEY: BriOsPbu4feZZr1jWZhVqNQI0mraSIKN3yzADZzIB5K1 # API Key replay EMS Tool
  IAM_DOMAIN: iam.cloud.ibm.com
  RUN_TIME_VERSION: 20.1
  HARDWARE_SPEC_NAME : M  # choose between these values["S", "M", "L", "XL"]
  HARDWARE_SPEC_NUM_NODES: 5 # Number of cores we want to engage, in [1, 2, 3, 4, 5]
  